parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: binidini
    database_user: root
    database_password: root
    mongo_server: mongodb://localhost:27017
    mongo_dbname: binidini
    mailer_transport: smtp
    mailer_host: smtp.yandex.ru
    mailer_user: info@tytymyty.ru
    mailer_password: rusden77
    smsc_login: tytymyty
    smsc_password: rusden77
    smsc_sender: tytymyty.ru
    yandex_token: WXQOYBYIOCT7RYVNNKLNUYOEFIBU3TRB76CEMO2JWUHBWJJYEPYQ
    locale: ru
    secret: HomoHomoniAmicusEst