imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!sms, !email, !alfabank]
        sms:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.sms.log
            level: info
            channels: [sms]
        email:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.email.log
            level: info
            channels: [email]
        alfabank:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.alfabank.log
            level: info
            channels: [alfabank]
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com
