imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            channels: [!sms, !email, !alfabank]
        sms:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.sms.log
            level: info
            channels: [sms]
        email:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.email.log
            level: info
            channels: [email]
        alfabank:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.alfabank.log
            level: info
            channels: [alfabank]
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
