binidini_search:
    resource: "@BinidiniSearchBundle/Resources/config/routing.yml"
    prefix:   /

binidini_api:
    resource: "@BinidiniApiBundle/Resources/config/routing.yml"
    prefix:   /api

binidini_web:
    resource: "@BinidiniWebBundle/Resources/config/routing/main.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"