binidini_search:
    resource: "@BinidiniSearchBundle/Resources/config/routing.yml"
    prefix:   /

binidini_api:
    resource: "@BinidiniApiBundle/Resources/config/routing.yml"
    prefix:   /api

binidini_web:
    resource: "@BinidiniWebBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
