# This file is part of the Binidini project.
# (c) Denis Manilo

binidini_api_shipping_bid_index:
    path: /shipping/{shipping_id}/bid
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.bid:indexAction
        _sylius:
            criteria:
                shipping: $shipping_id
            paginate: false
            sortable: true
            sorting:
                price: asc
            filterable: true

binidini_api_shipping_bid_new:
    path: /shipping/{shipping_id}/bid/new
    methods: [POST]
    defaults:
        _controller: binidini_core.controller.bid:createAction
        criteria:
            shipping: $shipping_id