binidini_api_carrier_shipping_index:
    path: /shipping/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                carrier: ['expr:service("security.context").getToken().getUser().getId()']
                state: $state

binidini_api_carrier_shipping_active:
    path: /shipping/active/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                carrier: ['expr:service("security.context").getToken().getUser().getId()']
                state: ['accepted', 'delivered', 'paid', 'rejected', 'refused', 'conflict']

binidini_api_carrier_shipping_active_new:
    path: /shipping/active_with_new/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                carrier: ['expr:service("security.context").getToken().getUser().getId()']
                state: ['new', 'accepted', 'delivered', 'paid', 'rejected', 'refused', 'conflict']

binidini_api_carrier_shipping_completed:
    path: /shipping/completed/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                carrier: ['expr:service("security.context").getToken().getUser().getId()']
                state: ['completed', 'canceled']

binidini_api_carrier_shipping_conflict:
    path: /shipping/conflict/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                carrier: ['expr:service("security.context").getToken().getUser().getId()']
                state: 'conflict'