binidini_api_user_reset_password:
    path: /password/reset
    methods: [POST, GET]
    defaults:
        _controller: BinidiniCoreBundle:User:resetPassword

binidini_api_user_create:
    path: /users/
    methods: [POST]
    defaults:
        _controller: BinidiniApiBundle:Registration:register