# This file is part of the Binidini project.
# (c) Denis Manilo

binidini_api_parcel_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.parcel:showAction

binidini_api_parcel_index:
    path: /
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.parcel:indexAction