binidini_api_payment_index:
    path: /
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.payment:indexAction
        _sylius:
            criteria:
                user: ['expr:service("security.context").getToken().getUser().getId()']
                state: ['completed']
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true

binidini_api_payment_new:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.payment:newAlfaAction

binidini_api_payment_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.payment:showAction
        _sylius:
            criteria:
                user: ['expr:service("security.context").getToken().getUser().getId()']

binidini_api_payment_refund:
    path: /refund
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.payment:refundAction

binidini_api_payment_new_success:
    path: /new/success
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.payment:depositAlfaSuccessAction

binidini_api_payment_new_fail:
    path: /new/fail
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.payment:depositAlfaFailAction