binidini_api_shipping_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:showAction

binidini_api_shipping_message_index:
    path: /{id}/messages/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.message:indexAction
        _sylius:
            paginate: false
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                shipping: $id

binidini_api_shipping_history_index:
    path: /{id}/history/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:historyIndexAction


binidini_api_shipping_state_transition:
    path: /{id}/state/{transition}
    methods: [POST]
    defaults:
        _controller: binidini_core.controller.shipping:updateStateAction

binidini_api_shipping_new:
    path: /new
    methods: [POST]
    defaults:
        _controller: binidini_core.controller.shipping:createAction

binidini_api_my_shipping_available_index:
    path: /sender/available
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                user: ['expr:service("security.context").getToken().getUser().getId()']
                state: ['new']

binidini_api_my_shipping_active_index:
    path: /sender/active
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                user: ['expr:service("security.context").getToken().getUser().getId()']
                state: ['accepted', 'delivered', 'paid', 'rejected', 'refused' , 'conflict']

binidini_api_my_shipping_active_index_new:
    path: /sender/active_with_new
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                user: ['expr:service("security.context").getToken().getUser().getId()']
                state: ['new', 'accepted', 'delivered', 'paid', 'rejected', 'refused', 'conflict']


binidini_api_my_shipping_conflict_index:
    path: /sender/conflict
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                user: ['expr:service("security.context").getToken().getUser().getId()']
                state: ['conflict']

binidini_api_my_shipping_completed_index:
    path: /sender/completed
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                user: ['expr:service("security.context").getToken().getUser().getId()']
                state: ['completed', 'canceled']