binidini_api_shipment_index:
    path: /
    methods: [GET]
    defaults:
        _controller: binidini_search.controller.shipment:indexAction
        _sylius:
            paginate: $limit
            sortable: true
            sorting:
                id: desc
            filterable: true