binidini_api_shipment_index:
    path: /
    methods: [GET]
    defaults:
        _controller: binidini_search.controller.shipment:indexAction
        _sylius:
            paginate: 100
            sortable: true
            sorting:
                id: desc
            filterable: true

binidini_api_search_shipment_search:
    path: /search
    methods: [GET]
    defaults:
        _controller: binidini_search.controller.shipment:searchAction
