binidini_api_shipping_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:showAction

binidini_api_shipping_message_index:
    path: /{id}/messages/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.message:indexAction
        _sylius:
            paginate: false
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                shipping: $id

binidini_api_shipping_history_index:
    path: /{id}/history/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:historyIndexAction


binidini_api_shipping_state_transition:
    path: /{id}/state/{transition}
    methods: [POST]
    defaults:
        _controller: binidini_core.controller.shipping:updateStateAction

binidini_api_shipping_new:
    path: /new
    methods: [POST]
    defaults:
        _controller: binidini_core.controller.shipping:createAction