binidini_api_user_index:
    path: /
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.user:indexAction
        _sylius:
            paginate:  $limit
            sortable:  true
            sorting:
                id: desc



binidini_api_user_update:
    path: /{id}
    methods: [PUT, PATCH]
    defaults:
        _controller: binidini_core.controller.user:updateAction


binidini_api_user_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: binidini_core.controller.user:deleteAction

binidini_api_user_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.user:showAction
