binidini_api_user_create:
    path: /
    methods: [POST]
    defaults:
        _controller: BinidiniApiBundle:Registration:register

binidini_api_user_index:
    path: /
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.user:indexAction
        _sylius:
            paginate:  $limit
            sortable:  true
            sorting:
                id: desc


binidini_api_user_update:
    path: /{id}
    methods: [POST]
    defaults:
        _controller: BinidiniApiBundle:Profile:edit


binidini_api_user_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: binidini_core.controller.user:deleteAction

binidini_api_user_show_current:
    path: /current
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.user:showAction
        _sylius:
            criteria:
                id: 'expr:service("security.context").getToken().getUser().getId()'

binidini_api_user_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.user:showAction

binidini_api_user_reset_password:
    path: /password/reset
    methods: [POST]
    defaults:
        _controller: BinidiniCoreBundle:User:resetPassword

