binidini_admin_shipping:
    path: /shipping
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                state: conflict
            template: BinidiniWebBundle::Backend/Shipping/index.html.twig

binidini_admin_shipping_resolve:
    path: /shipping/{id}/resolve
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:resolveAction

binidini_admin_shipping_show:
    path: /shipping/{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:showAction
        _sylius:
            template: BinidiniWebBundle:Backend/Shipping:show.html.twig
