binidini_admin_home:
    path: /
    methods: [GET]
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: binidini_admin_shipping
        permanent: true

binidini_admin_shipping:
    path: /shipping
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            repository:
                method: findByArguments
                arguments: [$id, $state, $deliveryPriceFrom, $deliveryPriceTo, $insurancePriceFrom, $insurancePriceTo, $deliveryTimeFrom, $deliveryTimeTo]
            paginate: $paginate
            filterable: true
            template: BinidiniWebBundle::Backend/Shipping/index.html.twig

binidini_admin_shipping_conflict:
    path: /conflicts
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                state: conflict
            template: BinidiniWebBundle::Backend/Shipping/index.html.twig

binidini_admin_shipping_resolve:
    path: /shipping/{id}/resolve
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:resolveAction

binidini_admin_shipping_show:
    path: /shipping/{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:showAction
        _sylius:
            template: BinidiniWebBundle:Backend/Shipping:show.html.twig

binidini_admin_user_index:
    path: /users
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.user:indexAction
        _sylius:
            repository:
                method: findByArguments
                arguments: [$phone, $lastName, $firstName, $parentName, $email, $registrationFrom, $registrationTo, $countOfCarriers, $countOfSenders, $blocked, $enabled]

            paginate: $paginate
            filterable: true
            template: BinidiniWebBundle::Backend/User/index.html.twig

binidini_admin_user_show:
    path: /user/{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.user:showAction
        _sylius:
            template: FOSUserBundle:Profile:show_admin.html.twig

binidini_admin_user_lock:
    path: /user/{id}/lock
    methods: [GET]
    defaults:
        _controller: BinidiniCoreBundle:User:lock

binidini_admin_user_unlock:
    path: /user/{id}/unlock
    methods: [GET]
    defaults:
        _controller: BinidiniCoreBundle:User:unlock

binidini_payment:
    resource: @BinidiniWebBundle/Resources/config/routing/backend/payment.yml
    prefix: /

binidini_admin_bid_index:
    path: /bid
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.bid:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            template: BinidiniWebBundle::Backend/Bid/index.html.twig