binidini_temp:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'BinidiniWebBundle:Static:temp.html.twig'

binidini__users_temp:
    path: /users/
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'BinidiniWebBundle:Static:temp.html.twig'

binidini_core_shipping_new:
    path: /shipping/new
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.shipping:createAction
        _sylius:
            template: BinidiniWebBundle:Frontend/Shipping:create.html.twig

binidini_core_shipping_index:
    path: /shipping
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                user: ['expr:service("security.context").getToken().getUser().getId()']
                state: $state
            template: BinidiniWebBundle:Frontend/Shipping:index.html.twig


binidini_core_shipping_show:
    path: /shipping/{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:showAction
        _sylius:
            template: BinidiniWebBundle:Frontend/Shipping:show.html.twig


binidini_search:
    path: /search
    methods: [GET]
    defaults:
        _controller: binidini_search.controller.shipment:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            template: BinidiniWebBundle:Frontend/Shipping:search.html.twig

binidini_core_transports:
    path: /transports
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                carrier: ['expr:service("security.context").getToken().getUser().getId()']
                state: $state
            template: BinidiniWebBundle:Frontend/Shipping:transports.html.twig


binidini_core_bid_new:
    path: /shipping/{shipping_id}/bid/new
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.bid:createAction
        _sylius:
            template: BinidiniWebBundle:Frontend/Bid:create.html.twig

binidini_core_bid_index:
    path: /shipping/{shipping_id}/bid
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.bid:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                shipping: $shipping_id
            template: BinidiniWebBundle:Frontend/Bid:index.html.twig


binidini_core_bid_show:
    path: /shipping/{shipping_id}/bid/{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.bid:showAction
        _sylius:
            template: BinidiniWebBundle:Frontend/Bid:show.html.twig
