binidini_api2_shipping_bid_index:
    path: /shipping/{shipping_id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.bid:indexAction
        _sylius:
            criteria:
                shipping: $shipping_id
            paginate: false
            sortable: true
            sorting:
                id: desc
            filterable: true