binidini_api2_shipping_message_index:
    path: /shipping/{shipping_id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.message:indexAction
        _sylius:
            paginate: false
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                shipping: $shipping_id