binidini_api2_shipping_review_index:
    path: /shipping/{shipping_id}/reviews/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.review:indexAction
        _sylius:
            paginate: 50
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                shipping: $shipping_id

binidini_api2_shipping_review_new:
    path: shipping/{shipping_id}/reviews/new
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.review:createAction