binidini_api2_shipping_list:
    path: /list
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:listAction

binidini_api2_shipping_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:oneShippingAction

binidini_api2_shipping_new:
    path: /
    methods: [POST]
    defaults:
        _controller: binidini_core.controller.shipping:createAction

binidini_api2_shipping_state_transition:
    path: /{id}/state/{transition}
    methods: [POST]
    defaults:
        _controller: binidini_core.controller.shipping:updateStateAction
    requirements:
        transition:  pay|complete|refuse|cancel|annul|dispute|debate


binidini_api2_shipping_deliver_transition:
    path: /{id}/deliver/
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.shipping:checkDeliveryCodeAction
