binidini_api2_user_get:
    path: /
    methods: [GET]
    defaults:
        _controller: BinidiniCoreBundle:User:getUser

binidini_api2_user_reset_password:
    path: /reset_password
    methods: [POST]
    defaults:
        _controller: BinidiniCoreBundle:User:resetUserPassword

binidini_api2_user_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: BinidiniCoreBundle:User:registerUser

binidini_api2_user_update:
    path: /update
    methods: [POST]
    defaults:
        _controller: BinidiniApiBundle:Profile:editUser