binidini_api_users:
    resource: @BinidiniApiBundle/Resources/config/routing/user.yml
    prefix: /users

binidini_api_carrier:
    resource: @BinidiniApiBundle/Resources/config/routing/carrier.yml
    prefix: /carrier

binidini_api_bids:
    resource: @BinidiniApiBundle/Resources/config/routing/bid.yml
    prefix: /bids

binidini_api_shipments:
    resource: @BinidiniApiBundle/Resources/config/routing/shipment.yml
    prefix: /shipments

binidini_api_shipping:
    resource: @BinidiniApiBundle/Resources/config/routing/shipping.yml
    prefix: /shipping