binidini_api_open:
    resource: @BinidiniApiBundle/Resources/config/routing/open.yml
    prefix: /open

binidini_api_users:
    resource: @BinidiniApiBundle/Resources/config/routing/user.yml
    prefix: /close/users

binidini_api_bids:
    resource: @BinidiniApiBundle/Resources/config/routing/bid.yml
    prefix: /close/bids

binidini_api_shipments:
    resource: @BinidiniApiBundle/Resources/config/routing/shipment.yml
    prefix: /close/shipments

binidini_api_shipping:
    resource: @BinidiniApiBundle/Resources/config/routing/shipping.yml
    prefix: /close/shipping