binidini_core_bid_new:
    path: /shipping/{shipping_id}/bid/new
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.bid:createAction
        _sylius:
            redirect:
                route: binidini_core_shipping_show
                parameters: { id: $shipping_id }

binidini_core_bid_index:
    path: /public/shipping/{shipping_id}/bid
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.bid:indexAction
        _sylius:
            criteria:
                shipping: $shipping_id
            paginate: false
            sortable: true
            sorting:
                id: desc
            filterable: true
            template: BinidiniWebBundle:Frontend/Bid:index.html.twig

binidini_core_shipping_bid_state_transition:
    path: /shipping/{shipping_id}/bid/{id}/state/{transition}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.bid:updateStateAction


binidini_user_bids_accepted:
    path: /user/bids/accepted
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.bid:indexAction
        _sylius:
            repository:
                method: findLast5DaysAcceptedBids
                arguments: ['expr:service("security.context").getToken().getUser().getId()']
            template: BinidiniWebBundle:Frontend/Bid:alert_accepted.html.twig

binidini_sender_bids_new:
    path: /sender/bids/new
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.bid:indexAction
        _sylius:
            repository:
                method: findLast5DaysNewBids
                arguments: ['expr:service("security.context").getToken().getUser().getId()']
            template: BinidiniWebBundle:Frontend/Bid:alert_new.html.twig
