binidini_core_bid_new:
    path: /shipping/{shipping_id}/bid/new
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.bid:createAction
        _sylius:
            redirect:
                route: binidini_core_shipping_show
                parameters: { id: $shipping_id }

binidini_core_bid_index:
    path: /shipping/{shipping_id}/bid
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.bid:indexAction
        _sylius:
            criteria:
                shipping: $shipping_id
            paginate: $paginate
            sortable: true
            sorting:
                price: asc
            filterable: true
            template: BinidiniWebBundle:Frontend/Bid:index.html.twig

binidini_core_shipping_bid_state_transition:
    path: /shipping/{shipping_id}/bid/{id}/state/{transition}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.bid:updateStateAction
        _sylius:
            redirect:
                route: binidini_core_shipping_show
                parameters: { id: $shipping_id }