binidini_core_bid_new:
    path: /shipping/{shipping_id}/bid/new
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.bid:createAction
        _sylius:
            redirect:
                route: binidini_core_shipping_show
                parameters: { id: $shipping_id }
            template: BinidiniWebBundle:Frontend/Bid:create.html.twig


binidini_core_bid_index:
    path: /shipping/{shipping_id}/bid
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.bid:indexAction
        _sylius:
            criteria:
                shipping: $shipping_id
            paginate: $paginate
            sortable: true
            sorting:
                price: desc
            filterable: true
            template: BinidiniWebBundle:Frontend/Bid:index.html.twig

binidini_core_bid_show:
    path: /shipping/{shipping_id}/bid/{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.bid:showAction
        _sylius:
            template: BinidiniWebBundle:Frontend/Bid:show.html.twig