binidini_email_confirm_send:
    path: /email/confirm/send
    methods: [GET]
    defaults:
        _controller: BinidiniCoreBundle:Email:sendConfirmEmail

binidini_email_confirm:
    path: /email/confirm/{token}
    methods: [GET]
    defaults:
        _controller: BinidiniCoreBundle:Email:confirm

binidini_unsubscribe_newsletter:
    path: /unsubscribe
    methods: [GET]
    defaults:
        _controller: BinidiniWebBundle:Default:unsubscribe