# This file is part of the Binidini package.
# (c) Denis MAnilo

binidini_home:
    path: /
    defaults:
        _controller: BinidiniWebBundle:Default:index

binidini_landing_page:
    path: /landing
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/landing.html.twig

binidini_shipping:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/shipping.yml
    prefix: /

binidini_shipment:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/shipment.yml
    prefix: /

binidini_message:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/message.yml
    prefix: /

binidini_bid:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/bid.yml
    prefix: /

binidini_profile:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/user.yml
    prefix: /

binidini_review:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/review.yml
    prefix: /

binidini_email:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/email.yml
    prefix: /

binidini_payment:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/payment.yml
    prefix: /