# This file is part of the Binidini package.
# (c) Denis MAnilo
binidini_home:
    path: /
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                user: ['expr:service("security.context").getToken().getUser().getId()']
                state: $state
            template: BinidiniWebBundle:Frontend/Shipping:index.html.twig

binidini_shipping:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/shipping.yml
    prefix: /

binidini_message:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/message.yml
    prefix: /

binidini_bid:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/bid.yml
    prefix: /

binidini_search:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/search.yml
    prefix: /

binidini_profile:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/user.yml
    prefix: /