# This file is part of the Binidini package.
# (c) Denis MAnilo

binidini_shipping:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/shipping.yml
    prefix: /

binidini_message:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/message.yml
    prefix: /

binidini_bid:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/bid.yml
    prefix: /

binidini_search:
    resource: @BinidiniWebBundle/Resources/config/routing/frontend/search.yml
    prefix: /