binidini_core_shipping_message_index:
    path: /public/shipping/{shipping_id}/messages/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.message:indexAction
        _sylius:
            paginate: false
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                shipping: $shipping_id
            template: BinidiniWebBundle:Frontend/Message:index.html.twig

binidini_core_shipping_message_new:
    path: shipping/{shipping_id}/messages/new
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.message:createAction
        _sylius:
            redirect:
                route: binidini_core_shipping_show
                parameters: { id: $shipping_id, tab: message }
            criteria:
                shipping: $shipping_id

binidini_my_messages:
    path: /messages/last
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.message:indexAction
        _sylius:
            repository:
                method: findLast15DaysMyNewMessages
                arguments: ['expr:service("security.context").getToken().getUser().getId()']
            template: BinidiniWebBundle:Frontend/Message:alert_new.html.twig

binidini_read_my_message:
    path: /shipping/{shipping_id}/message/{id}/state/{transition}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.message:updateStateAction
        _sylius:
            redirect:
                route: binidini_core_shipping_show
                parameters: { id: $shipping_id, tab: message }
