binidini_core_payment_index:
    path: /payment
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.payment:indexAction
        _sylius:
            criteria:
                user: ['expr:service("security.context").getToken().getUser().getId()']
                state: ['completed']
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            template: BinidiniWebBundle:Frontend/Payment:index.html.twig

binidini_core_payment_new:
    path: /payment/new
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.payment:newAlfaAction

binidini_core_payment_withdrawal:
    path: /payment/withdrawal
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.payment:withdrawalAction

binidini_core_payment_new_success:
    path: /payment/new/success
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.payment:depositAlfaSuccessAction

binidini_core_payment_new_fail:
    path: /payment/new/fail
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.payment:depositAlfaFailAction