binidini_core_user_from_review_index:
    path: /user/{user_id}/reviews/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.review:indexAction
        _sylius:
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                user: $user_id
            template: BinidiniWebBundle:Frontend/Review:user-index.html.twig

binidini_core_user_to_review_index:
    path: /user/{user_id}/reviews/to/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.review:indexAction
        _sylius:
            paginate: 50
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                userTo: $user_id
            template: BinidiniWebBundle:Frontend/Review:user-index.html.twig

binidini_core_shipping_review_index:
    path: /shipping/{shipping_id}/reviews/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.review:indexAction
        _sylius:
            paginate: 50
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                shipping: $shipping_id
            template: BinidiniWebBundle:Frontend/Review:shipping-index.html.twig

binidini_core_review_new:
    path: shipping/{shipping_id}/reviews/new
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.review:createAction
        _sylius:
            redirect:
                route: binidini_core_shipping_show
                parameters: { id: $shipping_id, tab: review }
            criteria:
                shipping: $shipping_id

