binidini_search:
    path: /search
    methods: [GET]
    defaults:
        _controller: binidini_search.controller.shipment:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            template: BinidiniWebBundle:Frontend/Shipping:search.html.twig