binidini_search_shipment_count:
    path: /public/shipment/count
    methods: [GET]
    defaults:
        _controller: binidini_search.controller.shipment:indexAction
        _sylius:
            template: BinidiniWebBundle:Frontend/Shipment:count.html.twig

binidini_search_shipment_index:
    path: /public/shipment
    methods: [GET]
    defaults:
        _controller: binidini_search.controller.shipment:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            template: BinidiniWebBundle:Frontend/Shipment:index.html.twig

binidini_search_shipment_private_index:
    path: /shipment
    methods: [GET]
    defaults:
        _controller: binidini_search.controller.shipment:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            template: BinidiniWebBundle:Frontend/Shipment:search.html.twig

binidini_search_shipment_search:
    path: /public/shipment/search
    methods: [GET, POST]
    defaults:
        _controller: binidini_search.controller.shipment:searchAction
        _sylius:
            paginate: $paginate
            sortable: true
            filterable: true
