binidini_core_shipping_new:
    path: /shipping/new
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.shipping:createAction
        _sylius:
            template: BinidiniWebBundle:Frontend/Shipping:create.html.twig

binidini_core_shipping_index:
    path: /sender/shipping
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                user: ['expr:service("security.context").getToken().getUser().getId()']
                state: $state
            template: BinidiniWebBundle:Frontend/Shipping:sender_index.html.twig

binidini_core_shipping_active_index:
    path: /sender/active/shipping
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                user: ['expr:service("security.context").getToken().getUser().getId()']
                state: ['new', 'accepted', 'delivered', 'paid', 'conflict']
            template: BinidiniWebBundle:Frontend/Shipping:shippings_active_index.html.twig

binidini_core_shipping_show:
    path: /public/shipping/{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:showAction
        _sylius:
            template: BinidiniWebBundle:Frontend/Shipping:show.html.twig


binidini_core_carrier_index:
    path: /carrier/shipping
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                carrier: ['expr:service("security.context").getToken().getUser().getId()']
                state: $state
            template: BinidiniWebBundle:Frontend/Shipping:carrier_index.html.twig

binidini_core_carrier_active_index:
    path: /carrier/active/shipping
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:indexAction
        _sylius:
            paginate: $paginate
            sortable: true
            sorting:
                id: desc
            filterable: true
            criteria:
                carrier: ['expr:service("security.context").getToken().getUser().getId()']
                state: ['accepted', 'delivered', 'paid', 'conflict']
            template: BinidiniWebBundle:Frontend/Shipping:carrier_active_index.html.twig

binidini_core_shipping_state_transition:
    path: /shipping/{id}/state/{transition}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:updateStateAction

binidini_core_shipping_deliver_transition:
    path: /shipping/{id}/deliver/
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:checkDeliveryCodeAction

binidini_core_shipping_history_index:
    path: /public/shipping/{id}/history
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.shipping:historyIndexAction
        _sylius:
            template: BinidiniWebBundle:Frontend/Shipping:history_index.html.twig

binidini_core_shipping_create_like:
    path: /shipping/like/{id}
    methods: [GET, POST]
    defaults:
        _controller: binidini_core.controller.shipping:createLikeAction
        _sylius:
            template: BinidiniWebBundle:Frontend/Shipping:create.html.twig