binidini_landing_page:
    path: /landing
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/landing.html.twig

binidini_rules:
    path: /rules
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/rules.html.twig

binidini_rules_api:
  path: /rules_api
  defaults:
    _controller: FrameworkBundle:Template:template
    template:    BinidiniWebBundle::Frontend/Static/rules_api.html.twig

binidini_about_api:
  path: /about_api
  defaults:
    _controller: FrameworkBundle:Template:template
    template:    BinidiniWebBundle::Frontend/Static/about_api.html.twig

binidini_rules_appendix_1:
    path: /rules/appendix_1
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/appendix_1.html.twig

binidini_rules_appendix_2:
    path: /rules/appendix_2
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/appendix_2.html.twig

binidini_rules_appendix_3:
    path: /rules/appendix_3
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/appendix_3.html.twig

binidini_rules_appendix_4:
    path: /rules/appendix_4
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/appendix_4.html.twig

binidini_how_it_works:
    path: /howitworks
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/howitworks.html.twig

binidini_payment:
    path: /payment
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/payment.html.twig

binidini_rest_api:
    path: /restapi
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/restapi.html.twig

binidini_partners:
    path: /partners
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/partners.html.twig

binidini_shops:
    path: /shops
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/shops.html.twig

binidini_carriers:
    path: /carriers
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/carriers.html.twig

binidini_senders:
    path: /senders
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/senders.html.twig

binidini_transporters:
    path: /transporters
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/transporters.html.twig

binidini_android_faq:
    path: /faq/android
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    BinidiniWebBundle::Frontend/Static/howitworks.html.twig
