binidini_core_change_password:
    path: /profile/change-password
    methods: [POST]
    defaults:
        _controller: BinidiniCoreBundle:User:changePassword

binidini_core_profile_show:
    path: /user/{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.user:showAction
        _sylius:
            template: FOSUserBundle:Profile:show.html.twig

binidini_core_reset_password:
    path: /resetting/password
    methods: [POST, GET]
    defaults:
        _controller: BinidiniCoreBundle:User:resetPassword
