binidini_core_profile_show:
    path: /profile/{id}
    methods: [GET]
    defaults:
        _controller: binidini_core.controller.user:showAction
        _sylius:
            template: FOSUserBundle:Profile:show.html.twig
