imports:
    - { resource: @BinidiniCoreBundle/Resources/config/resources.yml}
    - { resource: @BinidiniCoreBundle/Resources/config/state-machine.yml}

old_sound_rabbit_mq:
    connections:
        default:
            host:     'localhost'
            port:     5672
            user:     'guest'
            password: 'guest'
            vhost:    '/'
            lazy:     true
    producers:
        binidini_registration:
            connection:       default
            exchange_options: {name: 'binidini-registration', type: direct}
    consumers:
        binidini_registration:
            connection:       default
            exchange_options: {name: 'binidini-registration', type: direct}
            queue_options:    {name: 'binidini-registration'}
            callback:         binidini.registration_sms_service
