sylius_resource:
    settings:
        allowed_paginate: [10, 25, 50, 100]
        default_page_size: 25
        sortable: true
    resources:
        binidini_core.user:
            driver: doctrine/orm
            classes:
                model: Binidini\CoreBundle\Entity\User
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        binidini_core.shipping:
            driver: doctrine/orm
            classes:
                model: Binidini\CoreBundle\Entity\Shipping
                controller: Binidini\CoreBundle\Controller\ShippingController
                repository: Binidini\CoreBundle\Entity\ShippingRepository
        binidini_search.shipment:
            driver: doctrine/mongodb-odm
            classes:
                model: Binidini\SearchBundle\Document\Shipment
                controller: Binidini\SearchBundle\Controller\ShipmentController
                repository: Binidini\SearchBundle\Document\ShipmentRepository
        binidini_core.message:
            driver: doctrine/orm
            classes:
                model: Binidini\CoreBundle\Entity\Message
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        binidini_core.bid:
            driver: doctrine/orm
            classes:
                model: Binidini\CoreBundle\Entity\Bid
                controller: Binidini\CoreBundle\Controller\BidController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        binidini_core.review:
            driver: doctrine/orm
            classes:
                model: Binidini\CoreBundle\Entity\Review
                controller: Binidini\CoreBundle\Controller\ReviewController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository

