sylius_resource:
    settings:
        allowed_paginate: [15, 30, 60, 90]
        default_page_size: 15
        sortable: true
    resources:
        binidini_core.user:
            driver: doctrine/orm
            classes:
                model: Binidini\CoreBundle\Entity\User
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Binidini\CoreBundle\Entity\UserRepository
        binidini_core.shipping:
            driver: doctrine/orm
            classes:
                model: Binidini\CoreBundle\Entity\Shipping
                controller: Binidini\CoreBundle\Controller\ShippingController
                repository: Binidini\CoreBundle\Entity\ShippingRepository
        binidini_search.shipment:
            driver: doctrine/mongodb-odm
            classes:
                model: Binidini\SearchBundle\Document\Shipment
                controller: Binidini\SearchBundle\Controller\ShipmentController
                repository: Binidini\SearchBundle\Document\ShipmentRepository
        binidini_core.message:
            driver: doctrine/orm
            classes:
                model: Binidini\CoreBundle\Entity\Message
                controller: Binidini\CoreBundle\Controller\MessageController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        binidini_core.bid:
            driver: doctrine/orm
            classes:
                model: Binidini\CoreBundle\Entity\Bid
                controller: Binidini\CoreBundle\Controller\BidController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        binidini_core.review:
            driver: doctrine/orm
            classes:
                model: Binidini\CoreBundle\Entity\Review
                controller: Binidini\CoreBundle\Controller\ReviewController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        binidini_core.payment:
            driver: doctrine/orm
            classes:
                model: Binidini\CoreBundle\Entity\Payment
                controller: Binidini\CoreBundle\Controller\PaymentController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        binidini_core.gcm_token:
            driver: doctrine/orm
            classes:
                model: Binidini\CoreBundle\Entity\GcmToken
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        binidini_core.place:
            driver: doctrine/orm
            classes:
                model: Binidini\CoreBundle\Entity\Place
                controller: Binidini\CoreBundle\Controller\PlaceController
                repository: Binidini\CoreBundle\Entity\PlaceRepository
