services:
    binidini_user.registration.form.type:
        class: Binidini\CoreBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: binidini_user_registration }

    binidini_user.profile.form.type:
        class: Binidini\CoreBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: binidini_user_profile }

    binidini.subscriber.user_registration:
        class: Binidini\CoreBundle\EventListener\RegistrationListener
        arguments: [@old_sound_rabbit_mq.binidini_registration_producer]
        tags:
            - { name: kernel.event_subscriber }

    binidini.listener.user_aware:
        class: Binidini\CoreBundle\EventListener\UserAwareListener
        arguments: [@security.context]
        tags:
            - { name: kernel.event_listener, event: binidini_core.shipping.pre_create, method: setUser  }
            - { name: kernel.event_listener, event: binidini_core.bid.pre_create, method: setUser  }
            - { name: kernel.event_listener, event: binidini_core.message.pre_create, method: setUser  }
            - { name: kernel.event_listener, event: binidini_core.review.pre_create, method: setUser  }

    binidini.listener.shipping:
        class: Binidini\CoreBundle\EventListener\ShippingListener
        arguments: [@doctrine.odm.mongodb.document_manager]
        tags:
            - { name: kernel.event_listener, event: binidini_core.shipping.post_create, method: onShippingPostCreate }

    smsc.client:
        class: %guzzle.client.class%
        arguments: ['https://smsc.ru/']
        tags:
            - { name: guzzle.client }

    binidini.send_sms_service:
        class: Binidini\CoreBundle\Service\SendSmsService
        arguments:
            - @logger
            - @smsc.client
            - %smsc_login%
            - %smsc_password%
            - %smsc_sender%
        tags:
              - { name: monolog.logger, channel: sms }

    binidini.registration_sms_service:
        class: Binidini\CoreBundle\Worker\SendRegistrationSmsWorker
        arguments: [@binidini.send_sms_service]

    binidini.form.type.shipping:
        class: Binidini\CoreBundle\Form\Type\ShippingType
        tags:
            - { name: form.type, alias: binidini_core_shipping}

    binidini.form.type.message:
        class: Binidini\CoreBundle\Form\Type\MessageType
        tags:
            - { name: form.type, alias: binidini_core_message}

    binidini.form.type.bid:
        class: Binidini\CoreBundle\Form\Type\BidType
        tags:
            - { name: form.type, alias: binidini_core_bid}

    binidini.form.type.review:
            class: Binidini\CoreBundle\Form\Type\ReviewType
            tags:
                - { name: form.type, alias: binidini_core_review}

    binidini.security.service:
        class: Binidini\CoreBundle\Service\SecurityService
        arguments:
            - @security.context

    binidini.shipping.logic.service:
        class: Binidini\CoreBundle\Service\ShippingLogicService
        arguments:
            - @security.context
            - @doctrine.odm.mongodb.document_manager

    binidini.bid.logic.service:
        class: Binidini\CoreBundle\Service\BidLogicService
        arguments:
            - @security.context
            - @binidini.shipping.logic.service
            - @doctrine.orm.entity_manager
            - @sm.factory

    binidini.exceptions.listner:
        class: Binidini\CoreBundle\EventListener\ExceptionListener
        arguments: [@router, @session]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    binidini.listener.edit_user_profile:
        class: Binidini\CoreBundle\EventListener\EditUserProfileListener
        arguments: [@stof_doctrine_extensions.uploadable.manager, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: fos_user.profile.edit.completed }

    binidini.listener.shipping:
        class: Binidini\CoreBundle\EventListener\ReviewListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: binidini_core.review.post_create, method: onReviewPostCreate }