services:
    binidini_user.registration.form.type:
        class: Binidini\CoreBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: binidini_user_registration }

    binidini_user.profile.form.type:
        class: Binidini\CoreBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: binidini_user_profile }

    binidini.subscriber.user_registration:
        class: Binidini\CoreBundle\EventListener\RegistrationListener
        arguments: [@old_sound_rabbit_mq.binidini_sms_producer]
        tags:
            - { name: kernel.event_subscriber }

    binidini.listener.user_aware:
        class: Binidini\CoreBundle\EventListener\UserAwareListener
        arguments: [@security.context]
        tags:
            - { name: kernel.event_listener, event: binidini_core.shipping.pre_create, method: setUser  }
            - { name: kernel.event_listener, event: binidini_core.bid.pre_create, method: setUser  }
            - { name: kernel.event_listener, event: binidini_core.message.pre_create, method: setUser  }
            - { name: kernel.event_listener, event: binidini_core.review.pre_create, method: setUser  }

    binidini.listener.shipping:
        class: Binidini\CoreBundle\EventListener\ShippingListener
        arguments:
            - @doctrine.odm.mongodb.document_manager
            - @old_sound_rabbit_mq.binidini_geocode_producer
        tags:
            - { name: kernel.event_listener, event: binidini_core.shipping.post_create, method: onShippingPostCreate }
            - { name: kernel.event_listener, event: binidini_core.shipping.pre_create, method: onShippingPreCreate }

    binidini.listener.bid:
        class: Binidini\CoreBundle\EventListener\BidListener
        arguments: [@binidini.notification.service]
        tags:
            - { name: kernel.event_listener, event: binidini_core.bid.post_create, method: onBidPostCreate }

    binidini.geocode.yandex.client:
        class: %guzzle.client.class%
        arguments: ['http://geocode-maps.yandex.ru/1.x/']
        tags:
            - { name: guzzle.client }

    binidini.smsc.client:
        class: %guzzle.client.class%
        arguments: ['https://smsc.ru/']
        tags:
            - { name: guzzle.client }

    binidini.sms_service:
        class: Binidini\CoreBundle\Service\SmsService
        arguments:
            - @logger
            - @binidini.smsc.client
            - %smsc_login%
            - %smsc_password%
            - %smsc_sender%
        tags:
              - { name: monolog.logger, channel: sms }

    binidini.geocode_worker:
        class: Binidini\CoreBundle\Worker\GeocodeWorker
        arguments:
            - @binidini.geocode.yandex.client
            - @doctrine.orm.entity_manager
            - @doctrine.odm.mongodb.document_manager

    binidini.sms_worker:
        class: Binidini\CoreBundle\Worker\SmsWorker
        arguments: [@binidini.sms_service]

    binidini.email_worker:
        class: Binidini\CoreBundle\Worker\EmailWorker
        arguments:
            - @mailer
            - @logger
        tags:
              - { name: monolog.logger, channel: email }

    binidini.form.type.shipping:
        class: Binidini\CoreBundle\Form\Type\ShippingType
        tags:
            - { name: form.type, alias: binidini_core_shipping}

    binidini.form.type.message:
        class: Binidini\CoreBundle\Form\Type\MessageType
        tags:
            - { name: form.type, alias: binidini_core_message}

    binidini.form.type.bid:
        class: Binidini\CoreBundle\Form\Type\BidType
        tags:
            - { name: form.type, alias: binidini_core_bid}

    binidini.form.type.review:
            class: Binidini\CoreBundle\Form\Type\ReviewType
            tags:
                - { name: form.type, alias: binidini_core_review}

    binidini.security.service:
        class: Binidini\CoreBundle\Service\SecurityService
        arguments:
            - @security.context

    binidini.notification.service:
        class: Binidini\CoreBundle\Service\NotificationService
        arguments:
            - @old_sound_rabbit_mq.binidini_sms_producer
            - @old_sound_rabbit_mq.binidini_email_producer
            - @twig

    binidini.shipping.logic.service:
        class: Binidini\CoreBundle\Service\ShippingLogicService
        arguments:
            - @binidini.security.service
            - @doctrine.odm.mongodb.document_manager

    binidini.bid.logic.service:
        class: Binidini\CoreBundle\Service\BidLogicService
        arguments:
            - @binidini.security.service
            - @binidini.shipping.logic.service
            - @doctrine.orm.entity_manager
            - @sm.factory

    binidini.exceptions.listner:
        class: Binidini\CoreBundle\EventListener\ExceptionListener
        arguments: [@router, @session]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    binidini.listener.edit_user_profile:
        class: Binidini\CoreBundle\EventListener\EditUserProfileListener
        arguments: [@stof_doctrine_extensions.uploadable.manager, @doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: kernel.event_listener, event: fos_user.profile.edit.completed }
            - { name: kernel.event_listener, event: fos_user.profile.edit.success }
            - { name: kernel.event_listener, event: fos_user.profile.edit.initialize }

    binidini.listener.review:
        class: Binidini\CoreBundle\EventListener\ReviewListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: binidini_core.review.post_create, method: onReviewPostCreate }