winzou_state_machine:
    binidini_core_shipping:
        class: Binidini\CoreBundle\Entity\Shipping
        property_path: state
        graph: logic
        state_machine_class: Sylius\Component\Resource\StateMachine\StateMachine
        states:
            - init
            - new
            - accepted
            - paid          #awaiting_payment_confirmation
            - completed
            - rejected      # rejected by carrier, awaiting_cancel confirmation from sender
            - refused       # refused by sender, awaiting cancel confirmation from carrier
            - canceled
            - conflict
        transitions:
            create: #by sender
                from: [init]
                to: new
            accept: #by carrier
                from: [new]
                to: accepted
            pay:  #by sender
                from: [accepted]
                to: paid
            complete: #by carrier
                from: [paid]
                to: completed
            reject:  #by carrier
                from: [accepted, paid]
                to: rejected
            refuse:  #by sender
                from: [accepted, paid]
                to: refused
            cancel:  #by sender
                from: [new]
                to: canceled
            nullify:  #by sender
                from: [rejected]
                to: canceled
            annul:   #by carrier
                from: [refused]
                to: canceled
            dispute: #by sender
                from: [accepted, paid]
                to: conflict
            debate:  #by carrier
                from: [refused]
                to: conflict
            resolve:  #by manager
                from: [conflict]
                to: canceled
        callbacks:
            before:
                check_accept:   { on: 'accept',   do: [@binidini.security.service, 'checkCarrier'],    args: ['object'] }
                check_pay:      { on: 'pay',      do: [@binidini.security.service, 'checkSender'],    args: ['object'] }
                check_complete: { on: 'complete', do: [@binidini.shipping.logic.service, 'beforeComplete'], args: ['object'] }
                check_reject:   { on: 'reject',   do: [@binidini.security.service, 'checkResolver'],  args: ['object'] }
                check_refuse:   { on: 'refuse',   do: [@binidini.security.service, 'checkSender'],   args: ['object'] }
                check_cancel:   { on: 'cancel',   do: [@binidini.security.service, 'checkSender'],    args: ['object'] }
                check_nullify:  { on: 'nullify',  do: [@binidini.security.service, 'checkResolver'],  args: ['object'] }
                check_annul:    { on: 'annul',    do: [@binidini.security.service, 'checkResolver'],  args: ['object'] }
                check_dispute:  { on: 'dispute',  do: [@binidini.security.service, 'checkSender'],    args: ['object'] }
                check_debate:   { on: 'debate',   do: [@binidini.security.service, 'checkCarrier'],   args: ['object'] }
                check_resolve:  { on: 'resolve',  do: [@binidini.security.service, 'checkResolver'],  args: ['object'] }
            after:
                after_cancel:   { on: 'cancel',     do: [@binidini.shipping.logic.service, 'removeShipment'], args: ['object'] }
                after_pay:      { on: 'pay',        do: [@binidini.notification.service, 'notifyCarrier'],  args: ['object', '"pay_shipping"'] }
                after_complete: { on: 'complete',   do: [@binidini.notification.service, 'notifySender'],   args: ['object', '"complete_shipping"'] }
                after_debate:   { on: 'debate',     do: [@binidini.notification.service, 'notifySender'],   args: ['object', '"debate_shipping"'] }
                after_dispute:  { on: 'dispute',    do: [@binidini.notification.service, 'notifyCarrier'],  args: ['object', '"dispute_shipping"'] }
                after_refuse:   { on: 'refuse',     do: [@binidini.notification.service, 'notifyCarrier'],  args: ['object', '"refuse_shipping"'] }


    binidini_core_bid:
        class: Binidini\CoreBundle\Entity\Bid
        property_path: state
        graph: simple
        state_machine_class: Sylius\Component\Resource\StateMachine\StateMachine
        states:
            - init
            - new
            - accepted  #by sender
            - agreed    #by carrier
            - rejected  #by sender
            - canceled  #by carrier
        transitions:
            create: #by carrier
                from: [init]
                to: new
            accept: #by sender
                from: [new]
                to: accepted
            reject: #by sender
                from: [new]
                to: rejected
            cancel: #by carrier
                from: [new]
                to: canceled
            recall:
                from: [accepted]
                to: canceled
            agree:
                from: [accepted]
                to: agreed
        callbacks:
            before:
                before_accept: { on: 'accept', do: [@binidini.security.service, 'checkSender'],     args: ['object'] }
                before_reject: { on: 'reject', do: [@binidini.security.service, 'checkSender'],     args: ['object'] }
                before_cancel: { on: 'cancel', do: [@binidini.security.service, 'checkCarrier'],    args: ['object'] }
                before_recall: { on: 'recall', do: [@binidini.security.service, 'checkCarrier'],    args: ['object'] }
                before_agree:  { on: 'agree',  do: [@binidini.bid.logic.service, 'agreeTransition'], args: ['object'] }
            after:
                after_accept: { on: 'accept', do: [@binidini.notification.service, 'notifyCarrier'], args: ['object', '"accept_bid"']}
                after_reject: { on: 'reject', do: [@binidini.notification.service, 'notifyCarrier'], args: ['object', '"reject_bid"']}
                after_agreet: { on: 'agree',  do: [@binidini.notification.service, 'notifySender'],  args: ['object', '"agree_bid"']}
                after_recall: { on: 'recall', do: [@binidini.notification.service, 'notifySender'],  args: ['object', '"recall_bid"']}