<?php

namespace Binidini\CoreBundle\Form\Type;

use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\FormBuilderInterface;
use FOS\UserBundle\Form\Type\RegistrationFormType as RegistrationBaseType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class RegistrationFormType extends RegistrationBaseType
{

    private $class;
    private $routeName;

    public function __construct(Container $container, $class)
    {
        $request = $container->get('request');
        $this->routeName = $request->get('_route');
        $this->class = $class;
        parent::__construct($class); // TODO: Change the autogenerated stub
    }


    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);
        $builder->remove('email');
        $builder->remove("plainPassword");
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        if ($this->routeName == "binidini_api_user_create" || $this->routeName == "binidini_api2_user_create") {
            $resolver->setDefaults(array(
                'data_class' => $this->class,
                'intention'  => 'registration',
                'csrf_protection' => false
            ));
        } else {
            parent::setDefaultOptions($resolver);
        }

    }


    public function getName()
    {
        return 'binidini_user_registration';
    }

}